import '../models/transaction_model.dart';
import '../services/translation_service.dart';

class SampleData {
  // Sample Transactions
  static List<TransactionModel> get sampleTransactions => [
    TransactionModel(
      id: "1",
      trackingNumber: "FT123456789",
      senderName: "Current User",
      senderEmail: "user@flashtransfer.com",
      receiverName: "Jane Cooper",
      receiverEmail: "jane.cooper@email.com",
      amount: 396.84,
      currency: "USD",
      paymentMethod: "Credit Card",
      receivingMethod: "Bank Transfer",
      status: TransactionStatus.completed.toString().split('.').last,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      // UI properties
      type: TransactionType.send,
      recipient: "Jane Cooper",
      date: DateTime.now().subtract(const Duration(days: 1)),
      avatar: "assets/images/users/homeUser4.png",
      fee: 2.50,
      reference: "REF001",
    ),
    TransactionModel(
      id: "2",
      trackingNumber: "FT987654321",
      senderName: "John Doe",
      senderEmail: "john.doe@email.com",
      receiverName: "Current User",
      receiverEmail: "user@flashtransfer.com",
      amount: 250.00,
      currency: "EUR",
      paymentMethod: "Bank Transfer",
      receivingMethod: "Wallet",
      status: TransactionStatus.completed.toString().split('.').last,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      // UI properties
      type: TransactionType.receive,
      recipient: "Marvin McKinney",
      sender: "John Doe",
      date: DateTime.now().subtract(const Duration(days: 2)),
      avatar: "assets/images/users/homeUser1.png",
      fee: 1.25,
      reference: "REF002",
    ),
    TransactionModel(
      id: "3",
      trackingNumber: "FT456789123",
      senderName: "Current User",
      senderEmail: "user@flashtransfer.com",
      receiverName: "Esther Howard",
      receiverEmail: "esther.howard@email.com",
      amount: 150.75,
      currency: "GBP",
      paymentMethod: "Debit Card",
      receivingMethod: "Cash Pickup",
      status: TransactionStatus.pending.toString().split('.').last,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      // UI properties
      type: TransactionType.send,
      recipient: "Esther Howard",
      date: DateTime.now().subtract(const Duration(days: 3)),
      avatar: "assets/images/users/homeUser2.png",
      fee: 3.00,
      reference: "REF003",
    ),
    TransactionModel(
      id: "4",
      trackingNumber: "FT789123456",
      senderName: "Sarah Wilson",
      senderEmail: "sarah.wilson@email.com",
      receiverName: "Current User",
      receiverEmail: "user@flashtransfer.com",
      amount: 500.00,
      currency: "CAD",
      paymentMethod: "Bank Transfer",
      receivingMethod: "Bank Account",
      status: TransactionStatus.failed.toString().split('.').last,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      // UI properties
      type: TransactionType.receive,
      recipient: "Ralph Edwards",
      sender: "Sarah Wilson",
      date: DateTime.now().subtract(const Duration(days: 5)),
      avatar: "assets/images/users/homeUser3.png",
      fee: 0.00,
      reference: "REF004",
    ),
    TransactionModel(
      id: "5",
      trackingNumber: "FT321654987",
      senderName: "Current User",
      senderEmail: "user@flashtransfer.com",
      receiverName: "Michael Chen",
      receiverEmail: "michael.chen@email.com",
      amount: 0.025,
      currency: "BTC",
      paymentMethod: "Crypto Wallet",
      receivingMethod: "Crypto Wallet",
      status: TransactionStatus.processing.toString().split('.').last,
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      // UI properties
      type: TransactionType.send,
      recipient: "Michael Chen",
      date: DateTime.now().subtract(const Duration(hours: 6)),
      avatar: "assets/images/users/homeUser5.png",
      fee: 0.001,
      reference: "REF005",
      currencyType: CurrencyType.crypto,
    ),
    TransactionModel(
      id: "6",
      trackingNumber: "FT654987321",
      senderName: "Current User",
      senderEmail: "user@flashtransfer.com",
      receiverName: "Anna Rodriguez",
      receiverEmail: "anna.rodriguez@email.com",
      amount: 1250.00,
      currency: "USDT",
      paymentMethod: "Crypto Wallet",
      receivingMethod: "Crypto Wallet",
      status: TransactionStatus.completed.toString().split('.').last,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      // UI properties
      type: TransactionType.send,
      recipient: "Anna Rodriguez",
      date: DateTime.now().subtract(const Duration(days: 7)),
      avatar: "assets/images/users/homeUser6.png",
      fee: 5.00,
      reference: "REF006",
      currencyType: CurrencyType.crypto,
    ),
    TransactionModel(
      id: "7",
      trackingNumber: "FT147258369",
      senderName: "Emma Thompson",
      senderEmail: "emma.thompson@email.com",
      receiverName: "Current User",
      receiverEmail: "user@flashtransfer.com",
      amount: 75.25,
      currency: "USD",
      paymentMethod: "Credit Card",
      receivingMethod: "Bank Account",
      status: TransactionStatus.completed.toString().split('.').last,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      // UI properties
      type: TransactionType.receive,
      recipient: "David Wilson",
      sender: "Emma Thompson",
      date: DateTime.now().subtract(const Duration(days: 10)),
      avatar: "assets/images/users/homeUser7.png",
      fee: 1.50,
      reference: "REF007",
    ),
    TransactionModel(
      id: "8",
      trackingNumber: "FT963852741",
      senderName: "Current User",
      senderEmail: "user@flashtransfer.com",
      receiverName: "Lisa Garcia",
      receiverEmail: "lisa.garcia@email.com",
      amount: 2000.00,
      currency: "EUR",
      paymentMethod: "Bank Transfer",
      receivingMethod: "Bank Account",
      status: TransactionStatus.cancelled.toString().split('.').last,
      createdAt: DateTime.now().subtract(const Duration(days: 14)),
      // UI properties
      type: TransactionType.send,
      recipient: "Lisa Garcia",
      date: DateTime.now().subtract(const Duration(days: 14)),
      avatar: "assets/images/users/homeUser8.png",
      fee: 0.00,
      reference: "REF008",
    ),
  ];

  // Sample Recipients
  static List<RecipientModel> get sampleRecipients => [
    RecipientModel(
      id: "1",
      name: "Theresa Webb",
      country: "USA",
      flagAsset: "assets/images/flags/usa.png",
      avatar: "assets/images/users/homeUser1.png",
      lastSentAmount: 250.00,
      lastSentDate: DateTime.now().subtract(const Duration(days: 3)),
      isFavorite: true,
      totalTransactions: 12,
      totalAmountSent: 2450.00,
      email: "theresa.webb@email.com",
      phone: "+1-555-0123",
    ),
    RecipientModel(
      id: "2",
      name: "Kathryn Murphy",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser9.png",
      lastSentAmount: 180.50,
      lastSentDate: DateTime.now().subtract(const Duration(days: 7)),
      isFavorite: false,
      totalTransactions: 5,
      totalAmountSent: 890.25,
      email: "kathryn.murphy@email.com",
      phone: "+33-1-23-45-67-89",
    ),
    RecipientModel(
      id: "3",
      name: "Bessie Cooper",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser10.png",
      lastSentAmount: 320.75,
      lastSentDate: DateTime.now().subtract(const Duration(days: 12)),
      isFavorite: true,
      totalTransactions: 8,
      totalAmountSent: 1650.00,
      email: "bessie.cooper@email.com",
      phone: "+33-1-98-76-54-32",
    ),
    RecipientModel(
      id: "4",
      name: "Albert Flores",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser11.png",
      lastSentAmount: 95.00,
      lastSentDate: DateTime.now().subtract(const Duration(days: 20)),
      isFavorite: false,
      totalTransactions: 3,
      totalAmountSent: 285.00,
      email: "albert.flores@email.com",
      phone: "+33-1-11-22-33-44",
    ),
    RecipientModel(
      id: "5",
      name: "Devon Lane",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/blog-user-1.png",
      lastSentAmount: 450.00,
      lastSentDate: DateTime.now().subtract(const Duration(days: 2)),
      isFavorite: true,
      totalTransactions: 15,
      totalAmountSent: 3200.00,
      email: "devon.lane@email.com",
      phone: "+33-1-55-66-77-88",
    ),
    RecipientModel(
      id: "6",
      name: "Jenny Wilson",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser12.png",
      lastSentAmount: 125.25,
      lastSentDate: DateTime.now().subtract(const Duration(days: 30)),
      isFavorite: false,
      totalTransactions: 2,
      totalAmountSent: 250.50,
      email: "jenny.wilson@email.com",
      phone: "+33-1-99-88-77-66",
    ),
    RecipientModel(
      id: "7",
      name: "Marvin McKinney",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser2.png",
      lastSentAmount: 200.00,
      lastSentDate: DateTime.now().subtract(const Duration(days: 5)),
      isFavorite: false,
      totalTransactions: 7,
      totalAmountSent: 1400.00,
      email: "marvin.mckinney@email.com",
      phone: "+33-1-44-55-66-77",
    ),
    RecipientModel(
      id: "8",
      name: "Robert Fox",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser3.png",
      lastSentAmount: 75.50,
      lastSentDate: DateTime.now().subtract(const Duration(days: 45)),
      isFavorite: false,
      totalTransactions: 1,
      totalAmountSent: 75.50,
      email: "robert.fox@email.com",
      phone: "+33-1-22-33-44-55",
    ),
  ];

  // Sample Invites
  static List<InviteModel> get sampleInvites => [
    InviteModel(
      id: "1",
      name: "Theresa Webb",
      email: "theresa.webb@email.com",
      country: "USA",
      flagAsset: "assets/images/flags/usa.png",
      avatar: "assets/images/users/homeUser1.png",
      status: InviteStatus.completed,
      dateInvited: DateTime.now().subtract(const Duration(days: 30)),
      dateAccepted: DateTime.now().subtract(const Duration(days: 25)),
      dateCompleted: DateTime.now().subtract(const Duration(days: 20)),
      rewardAmount: 25.00,
      referralCode: "REF123456",
    ),
    InviteModel(
      id: "2",
      name: "Kathryn Murphy",
      email: "kathryn.murphy@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser9.png",
      status: InviteStatus.accepted,
      dateInvited: DateTime.now().subtract(const Duration(days: 15)),
      dateAccepted: DateTime.now().subtract(const Duration(days: 10)),
      referralCode: "REF789012",
    ),
    InviteModel(
      id: "3",
      name: "Bessie Cooper",
      email: "bessie.cooper@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser10.png",
      status: InviteStatus.pending,
      dateInvited: DateTime.now().subtract(const Duration(days: 5)),
      referralCode: "REF345678",
    ),
    InviteModel(
      id: "4",
      name: "Albert Flores",
      email: "albert.flores@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser11.png",
      status: InviteStatus.expired,
      dateInvited: DateTime.now().subtract(const Duration(days: 60)),
      referralCode: "REF901234",
    ),
    InviteModel(
      id: "5",
      name: "Devon Lane",
      email: "devon.lane@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/blog-user-1.png",
      status: InviteStatus.completed,
      dateInvited: DateTime.now().subtract(const Duration(days: 45)),
      dateAccepted: DateTime.now().subtract(const Duration(days: 40)),
      dateCompleted: DateTime.now().subtract(const Duration(days: 35)),
      rewardAmount: 25.00,
      referralCode: "REF567890",
    ),
    InviteModel(
      id: "6",
      name: "Jenny Wilson",
      phone: "+33-1-99-88-77-66",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser12.png",
      status: InviteStatus.pending,
      dateInvited: DateTime.now().subtract(const Duration(days: 2)),
      referralCode: "REF234567",
    ),
    InviteModel(
      id: "7",
      name: "Marvin McKinney",
      email: "marvin.mckinney@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser2.png",
      status: InviteStatus.accepted,
      dateInvited: DateTime.now().subtract(const Duration(days: 8)),
      dateAccepted: DateTime.now().subtract(const Duration(days: 3)),
      referralCode: "REF678901",
    ),
    InviteModel(
      id: "8",
      name: "Robert Fox",
      email: "robert.fox@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser3.png",
      status: InviteStatus.pending,
      dateInvited: DateTime.now().subtract(const Duration(hours: 12)),
      referralCode: "REF890123",
    ),
  ];

  // Sample Privacy Sections - Now using TranslationService
  static List<PrivacySectionModel> get samplePrivacySections {
    final tr = TranslationService.instance.translate;
    
    return [
      PrivacySectionModel(
        id: "introduction",
        title: tr('privacy.sections.introduction.title'),
        content: tr('privacy.sections.introduction.content'),
      ),
      PrivacySectionModel(
        id: "dataCollection", 
        title: tr('privacy.sections.dataCollection.title'),
        content: tr('privacy.sections.dataCollection.content'),
        subsections: [
          PrivacySectionModel(
            id: "personalInfo",
            title: tr('privacy.sections.dataCollection.personalInfo.title'),
            content: tr('privacy.sections.dataCollection.personalInfo.content'),
          ),
          PrivacySectionModel(
            id: "nonPersonalInfo",
            title: tr('privacy.sections.dataCollection.nonPersonalInfo.title'),
            content: tr('privacy.sections.dataCollection.nonPersonalInfo.content'),
          ),
        ],
      ),
      PrivacySectionModel(
        id: "dataUsage",
        title: tr('privacy.sections.dataUsage.title'),
        content: tr('privacy.sections.dataUsage.content'),
        subsections: [
          PrivacySectionModel(
            id: "processing",
            title: tr('privacy.subsections.transactionProcessing.title'),
            content: tr('privacy.sections.dataUsage.processing'),
          ),
          PrivacySectionModel(
            id: "security",
            title: tr('privacy.subsections.securityFraudPrevention.title'), 
            content: tr('privacy.sections.dataUsage.security'),
          ),
          PrivacySectionModel(
            id: "communication",
            title: tr('privacy.subsections.communications.title'),
            content: tr('privacy.sections.dataUsage.communication'),
          ),
        ],
      ),
      PrivacySectionModel(
        id: "dataSharing",
        title: tr('privacy.sections.dataSharing.title'),
        content: tr('privacy.sections.dataSharing.content'),
        subsections: [
          PrivacySectionModel(
            id: "serviceProviders",
            title: tr('privacy.subsections.serviceProviders.title'),
            content: tr('privacy.sections.dataSharing.serviceProviders'),
          ),
          PrivacySectionModel(
            id: "legal",
            title: tr('privacy.subsections.legalRequirements.title'),
            content: tr('privacy.sections.dataSharing.legal'),
          ),
        ],
      ),
      PrivacySectionModel(
        id: "dataSecurity",
        title: tr('privacy.sections.dataSecurity.title'),
        content: tr('privacy.sections.dataSecurity.content'),
      ),
      PrivacySectionModel(
        id: "userRights",
        title: tr('privacy.sections.userRights.title'),
        content: tr('privacy.sections.userRights.content'),
      ),
      PrivacySectionModel(
        id: "cookies",
        title: tr('privacy.sections.cookies.title'),
        content: tr('privacy.sections.cookies.content'),
      ),
      PrivacySectionModel(
        id: "thirdParty",
        title: tr('privacy.sections.thirdParty.title'),
        content: tr('privacy.sections.thirdParty.content'),
      ),
      PrivacySectionModel(
        id: "dataRetention",
        title: tr('privacy.sections.dataRetention.title'),
        content: tr('privacy.sections.dataRetention.content'),
      ),
      PrivacySectionModel(
        id: "international",
        title: tr('privacy.sections.international.title'),
        content: tr('privacy.sections.international.content'),
      ),
      PrivacySectionModel(
        id: "minors",
        title: tr('privacy.sections.minors.title'),
        content: tr('privacy.sections.minors.content'),
      ),
      PrivacySectionModel(
        id: "changes",
        title: tr('privacy.sections.changes.title'),
        content: tr('privacy.sections.changes.content'),
      ),
      PrivacySectionModel(
        id: "contact",
        title: tr('privacy.sections.contact.title'),
        content: tr('privacy.sections.contact.content'),
      ),
    ];
  }

  // Sample referral statistics
  static Map<String, dynamic> get referralStats => {
    'totalInvited': 47,
    'successfulReferrals': 12,
    'totalEarned': 300.00,
    'pendingRewards': 75.00,
    'referralCode': 'FLASH2024',
    'referralLink': 'https://flashtransfer.com/ref/FLASH2024',
  };
}
