import '../models/transaction_model.dart';

class SampleData {
  // Sample Transactions
  static List<TransactionModel> get sampleTransactions => [
    TransactionModel(
      id: "1",
      type: TransactionType.send,
      amount: 396.84,
      currency: "USD",
      recipient: "Jane Cooper",
      date: DateTime.now().subtract(const Duration(days: 1)),
      status: TransactionStatus.completed,
      avatar: "assets/images/users/homeUser4.png",
      fee: 2.50,
      reference: "REF001",
      trackingNumber: "FT123456789",
    ),
    TransactionModel(
      id: "2", 
      type: TransactionType.receive,
      amount: 250.00,
      currency: "EUR",
      recipient: "Marvin McKinney",
      sender: "John Doe",
      date: DateTime.now().subtract(const Duration(days: 2)),
      status: TransactionStatus.completed,
      avatar: "assets/images/users/homeUser1.png",
      fee: 1.25,
      reference: "REF002",
      trackingNumber: "FT987654321",
    ),
    TransactionModel(
      id: "3",
      type: TransactionType.send,
      amount: 150.75,
      currency: "GBP", 
      recipient: "Esther Howard",
      date: DateTime.now().subtract(const Duration(days: 3)),
      status: TransactionStatus.pending,
      avatar: "assets/images/users/homeUser2.png",
      fee: 3.00,
      reference: "REF003",
      trackingNumber: "FT456789123",
    ),
    TransactionModel(
      id: "4",
      type: TransactionType.receive,
      amount: 500.00,
      currency: "CAD",
      recipient: "Ralph Edwards", 
      sender: "Sarah Wilson",
      date: DateTime.now().subtract(const Duration(days: 5)),
      status: TransactionStatus.failed,
      avatar: "assets/images/users/homeUser3.png",
      fee: 0.00,
      reference: "REF004",
      trackingNumber: "FT789123456",
    ),
    TransactionModel(
      id: "5",
      type: TransactionType.send,
      amount: 0.025,
      currency: "BTC",
      recipient: "Michael Chen",
      date: DateTime.now().subtract(const Duration(hours: 6)),
      status: TransactionStatus.processing,
      avatar: "assets/images/users/homeUser5.png",
      fee: 0.001,
      reference: "REF005",
      trackingNumber: "FT321654987",
      currencyType: CurrencyType.crypto,
    ),
    TransactionModel(
      id: "6",
      type: TransactionType.send,
      amount: 1250.00,
      currency: "USDT", 
      recipient: "Anna Rodriguez",
      date: DateTime.now().subtract(const Duration(days: 7)),
      status: TransactionStatus.completed,
      avatar: "assets/images/users/homeUser6.png",
      fee: 5.00,
      reference: "REF006",
      trackingNumber: "FT654987321",
      currencyType: CurrencyType.crypto,
    ),
    TransactionModel(
      id: "7",
      type: TransactionType.receive,
      amount: 75.25,
      currency: "USD",
      recipient: "David Wilson",
      sender: "Emma Thompson", 
      date: DateTime.now().subtract(const Duration(days: 10)),
      status: TransactionStatus.completed,
      avatar: "assets/images/users/homeUser7.png",
      fee: 1.50,
      reference: "REF007", 
      trackingNumber: "FT147258369",
    ),
    TransactionModel(
      id: "8",
      type: TransactionType.send,
      amount: 2000.00,
      currency: "EUR",
      recipient: "Lisa Garcia",
      date: DateTime.now().subtract(const Duration(days: 14)),
      status: TransactionStatus.cancelled,
      avatar: "assets/images/users/homeUser8.png",
      fee: 0.00,
      reference: "REF008",
      trackingNumber: "FT963852741",
    ),
  ];

  // Sample Recipients
  static List<RecipientModel> get sampleRecipients => [
    RecipientModel(
      id: "1",
      name: "Theresa Webb",
      country: "USA",
      flagAsset: "assets/images/flags/usa.png",
      avatar: "assets/images/users/homeUser1.png",
      lastSentAmount: 250.00,
      lastSentDate: DateTime.now().subtract(const Duration(days: 3)),
      isFavorite: true,
      totalTransactions: 12,
      totalAmountSent: 2450.00,
      email: "theresa.webb@email.com",
      phone: "+1-555-0123",
    ),
    RecipientModel(
      id: "2",
      name: "Kathryn Murphy",
      country: "France", 
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser9.png",
      lastSentAmount: 180.50,
      lastSentDate: DateTime.now().subtract(const Duration(days: 7)),
      isFavorite: false,
      totalTransactions: 5,
      totalAmountSent: 890.25,
      email: "kathryn.murphy@email.com",
      phone: "+33-1-23-45-67-89",
    ),
    RecipientModel(
      id: "3",
      name: "Bessie Cooper", 
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser10.png",
      lastSentAmount: 320.75,
      lastSentDate: DateTime.now().subtract(const Duration(days: 12)),
      isFavorite: true,
      totalTransactions: 8,
      totalAmountSent: 1650.00,
      email: "bessie.cooper@email.com",
      phone: "+33-1-98-76-54-32",
    ),
    RecipientModel(
      id: "4",
      name: "Albert Flores",
      country: "France",
      flagAsset: "assets/images/flags/france.png", 
      avatar: "assets/images/users/homeUser11.png",
      lastSentAmount: 95.00,
      lastSentDate: DateTime.now().subtract(const Duration(days: 20)),
      isFavorite: false,
      totalTransactions: 3,
      totalAmountSent: 285.00,
      email: "albert.flores@email.com",
      phone: "+33-1-11-22-33-44",
    ),
    RecipientModel(
      id: "5",
      name: "Devon Lane",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/blog-user-1.png",
      lastSentAmount: 450.00,
      lastSentDate: DateTime.now().subtract(const Duration(days: 2)),
      isFavorite: true,
      totalTransactions: 15,
      totalAmountSent: 3200.00,
      email: "devon.lane@email.com", 
      phone: "+33-1-55-66-77-88",
    ),
    RecipientModel(
      id: "6",
      name: "Jenny Wilson",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser12.png",
      lastSentAmount: 125.25,
      lastSentDate: DateTime.now().subtract(const Duration(days: 30)),
      isFavorite: false,
      totalTransactions: 2,
      totalAmountSent: 250.50,
      email: "jenny.wilson@email.com",
      phone: "+33-1-99-88-77-66",
    ),
    RecipientModel(
      id: "7",
      name: "Marvin McKinney",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser2.png",
      lastSentAmount: 200.00,
      lastSentDate: DateTime.now().subtract(const Duration(days: 5)),
      isFavorite: false,
      totalTransactions: 7,
      totalAmountSent: 1400.00,
      email: "marvin.mckinney@email.com",
      phone: "+33-1-44-55-66-77",
    ),
    RecipientModel(
      id: "8",
      name: "Robert Fox",
      country: "France", 
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser3.png",
      lastSentAmount: 75.50,
      lastSentDate: DateTime.now().subtract(const Duration(days: 45)),
      isFavorite: false,
      totalTransactions: 1,
      totalAmountSent: 75.50,
      email: "robert.fox@email.com",
      phone: "+33-1-22-33-44-55",
    ),
  ];

  // Sample Invites
  static List<InviteModel> get sampleInvites => [
    InviteModel(
      id: "1",
      name: "Theresa Webb",
      email: "theresa.webb@email.com",
      country: "USA", 
      flagAsset: "assets/images/flags/usa.png",
      avatar: "assets/images/users/homeUser1.png",
      status: InviteStatus.completed,
      dateInvited: DateTime.now().subtract(const Duration(days: 30)),
      dateAccepted: DateTime.now().subtract(const Duration(days: 25)),
      dateCompleted: DateTime.now().subtract(const Duration(days: 20)),
      rewardAmount: 25.00,
      referralCode: "REF123456",
    ),
    InviteModel(
      id: "2",
      name: "Kathryn Murphy",
      email: "kathryn.murphy@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser9.png",
      status: InviteStatus.accepted,
      dateInvited: DateTime.now().subtract(const Duration(days: 15)),
      dateAccepted: DateTime.now().subtract(const Duration(days: 10)),
      referralCode: "REF789012",
    ),
    InviteModel(
      id: "3",
      name: "Bessie Cooper",
      email: "bessie.cooper@email.com", 
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser10.png",
      status: InviteStatus.pending,
      dateInvited: DateTime.now().subtract(const Duration(days: 5)),
      referralCode: "REF345678",
    ),
    InviteModel(
      id: "4",
      name: "Albert Flores",
      email: "albert.flores@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser11.png",
      status: InviteStatus.expired,
      dateInvited: DateTime.now().subtract(const Duration(days: 60)),
      referralCode: "REF901234",
    ),
    InviteModel(
      id: "5",
      name: "Devon Lane",
      email: "devon.lane@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/blog-user-1.png",
      status: InviteStatus.completed,
      dateInvited: DateTime.now().subtract(const Duration(days: 45)),
      dateAccepted: DateTime.now().subtract(const Duration(days: 40)),
      dateCompleted: DateTime.now().subtract(const Duration(days: 35)), 
      rewardAmount: 25.00,
      referralCode: "REF567890",
    ),
    InviteModel(
      id: "6",
      name: "Jenny Wilson",
      phone: "+33-1-99-88-77-66",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser12.png",
      status: InviteStatus.pending,
      dateInvited: DateTime.now().subtract(const Duration(days: 2)),
      referralCode: "REF234567",
    ),
    InviteModel(
      id: "7",
      name: "Marvin McKinney", 
      email: "marvin.mckinney@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser2.png",
      status: InviteStatus.accepted,
      dateInvited: DateTime.now().subtract(const Duration(days: 8)),
      dateAccepted: DateTime.now().subtract(const Duration(days: 3)),
      referralCode: "REF678901",
    ),
    InviteModel(
      id: "8",
      name: "Robert Fox",
      email: "robert.fox@email.com",
      country: "France",
      flagAsset: "assets/images/flags/france.png",
      avatar: "assets/images/users/homeUser3.png", 
      status: InviteStatus.pending,
      dateInvited: DateTime.now().subtract(const Duration(hours: 12)),
      referralCode: "REF890123",
    ),
  ];

  // Sample Privacy Sections  
  static List<PrivacySectionModel> get samplePrivacySections => [
    PrivacySectionModel(
      id: "introduction",
      title: "Introduction",
      content: "At Flash Transfer, we respect your privacy. This Privacy Policy outlines how we collect, use, and protect your personal information.",
    ),
    PrivacySectionModel(
      id: "dataCollection",
      title: "1. Information We Collect",
      content: "We collect various types of information to provide and improve our services:",
      subsections: [
        PrivacySectionModel(
          id: "personalInfo",
          title: "Personal Information",
          content: "Name, email, phone number, payment details, and transaction history.",
        ),
        PrivacySectionModel(
          id: "nonPersonalInfo", 
          title: "Non-Personal Information",
          content: "Device data, IP address, and app usage statistics.",
        ),
      ],
    ),
    PrivacySectionModel(
      id: "dataUsage",
      title: "2. How We Use Your Information",
      content: "We use your information for the following purposes:",
      subsections: [
        PrivacySectionModel(
          id: "processing",
          title: "Transaction Processing",
          content: "To process money transfers and manage your account.",
        ),
        PrivacySectionModel(
          id: "security",
          title: "Security & Fraud Prevention", 
          content: "For fraud prevention and security purposes.",
        ),
        PrivacySectionModel(
          id: "communication",
          title: "Communications",
          content: "To send you updates or promotional materials (with your consent).",
        ),
      ],
    ),
    PrivacySectionModel(
      id: "dataSharing",
      title: "3. Sharing Your Information", 
      content: "We may share your information in limited circumstances:",
      subsections: [
        PrivacySectionModel(
          id: "serviceProviders",
          title: "Service Providers",
          content: "With service providers (payment processors, identity verification).",
        ),
        PrivacySectionModel(
          id: "legal",
          title: "Legal Requirements",
          content: "For legal purposes or to prevent fraud.",
        ),
      ],
    ),
    PrivacySectionModel(
      id: "dataSecurity",
      title: "4. Data Security",
      content: "We use encryption and other security measures to protect your data, but no system is entirely secure.",
    ),
    PrivacySectionModel(
      id: "userRights",
      title: "5. Your Rights",
      content: "You can access, update, or delete your personal information. You can also opt-out of marketing communications.",
    ),
  ];

  // Sample referral statistics
  static Map<String, dynamic> get referralStats => {
    'totalInvited': 47,
    'successfulReferrals': 12,
    'totalEarned': 300.00,
    'pendingRewards': 75.00,
    'referralCode': 'FLASH2024',
    'referralLink': 'https://flashtransfer.com/ref/FLASH2024',
  };
}